<?php
namespace ThemeInfrastructure\ACF;

class ACFFlexFields
{
	public static function setupACFFlex()
	{
		self::setupFlexFields();
	}

	private static function setupFlexFields()
	{
		if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_flex_fields',
			'title' => 'Flex Fields',
			'fields' => array(
				array(
					'key' => 'field_flex_fields',
					'label' => '',
					'name' => 'flexible_content',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),

					// Layouts Start Here ------------------------------------------------
					'layouts' => array(

						// 50/50 -----------------------------------------------------------
						'50_50_layout' => array(
							'key' => 'field_flex_50_50',
							'name' => '50_50',
							'label' => '50/50',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_50_50_background_color_flex',
									'label' => 'Select Background Color',
									'name' => '50_50_background_color',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'white' => 'White',
										'gray' => 'Light Gray',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'white',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_flex_50_50_section_divider',
									'label' => 'Section Divider',
									'name' => '50_50_section_divider',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'yes' => 'Add Divider',
									),
									'allow_custom' => 0,
									'default_value' => array(
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
									'save_custom' => 0,
								),
								array(
									'key' => 'field_flex_50_50_section_headline',
									'label' => 'Section Headline',
									'name' => '50_50_section_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_flex_50_50_section_intro',
									'label' => 'Section Introduction',
									'name' => '50_50_section_intro',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'rows' => 3,
									'maxlength' => '',
								),
								array(
									'key' => 'field_flex_50_50_left',
									'label' => 'Left Content',
									'name' => '50_50_left',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_flex_50_50_left_headline',
											'label' => 'Headline',
											'name' => '50_50_left_headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_flex_50_50_left_content',
											'label' => 'Content',
											'name' => '50_50_left_content',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
											'delay' => 0,
										),
										array(
											'key' => 'flex_field_left_50_50_button_label',
											'label' => 'Button Label',
											'name' => '50_50_left_button_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_left_50_50_button_link',
											'label' => 'Button Link',
											'name' => '50_50_left_button_url',
											'type' => 'url',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array(
											'key' => 'flex_field_left_50_50_button_link_behavior',
											'label' => 'Link Behavior',
											'name' => 'link_behavior',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'standard-link' => 'Standard Link',
												'pdf-download' => 'PDF Download',
												'new-tab' => 'Open in a new tab',
											),
											'allow_custom' => 0,
											'default_value' => 'standard-link',
											'layout' => 'horizontal',
											'toggle' => 0,
											'return_format' => 'value',
											'save_custom' => 0,
										),
									),
								),
								array(
									'key' => 'field_flex_50_50_right',
									'label' => 'Right Content',
									'name' => '50_50_right',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_flex_50_50_right_headline',
											'label' => 'Headline',
											'name' => '50_50_right_headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_flex_50_50_right_content',
											'label' => 'Content',
											'name' => '50_50_right_content',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
											'delay' => 0,
										),
										array(
											'key' => 'flex_field_right_50_50_button_label',
											'label' => 'Button Label',
											'name' => '50_50_right_button_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_right_50_50_button_link',
											'label' => 'Button Link',
											'name' => '50_50_right_button_url',
											'type' => 'url',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array(
											'key' => 'flex_field_right_50_50_button_link_behavior',
											'label' => 'Link Behavior',
											'name' => 'link_behavior',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'standard-link' => 'Standard Link',
												'pdf-download' => 'PDF Download',
												'new-tab' => 'Open in a new tab',
											),
											'allow_custom' => 0,
											'default_value' => 'standard-link',
											'layout' => 'horizontal',
											'toggle' => 0,
											'return_format' => 'value',
											'save_custom' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),

						// Image with Text -------------------------------------------------
						'image_text_layout' => array(
							'key' => 'flex_field_image_text',
							'name' => 'image_with_text',
							'label' => 'Image with Text',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_image_text_image',
									'label' => 'Image',
									'name' => 'image_text_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'flex_field_image_text_image_alignment',
									'label' => 'Select Image Alignment',
									'name' => 'image_text_alignment_options',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'left-align' => 'Left Align',
										'right-align' => 'Right Align',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'left-align',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'flex_field_image_text_headline',
									'label' => 'Headline',
									'name' => 'image_text_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '100',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_image_text_content',
									'label' => 'Content',
									'name' => 'image_text_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '100',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_image_text_quick_links',
									'label' => 'Quick Links',
									'name' => 'quick_link_repeater',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'field_quick_link_label',
											'label' => 'Link Label',
											'name' => 'link_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_quick_link_url',
											'label' => 'Link URL',
											'name' => 'link_url',
											'type' => 'url',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array(
											'key' => 'field_quick_link_behavior',
											'label' => 'Link Behavior',
											'name' => 'link_behavior',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '20',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'standard-link' => 'Standard Link',
												'pdf-download' => 'PDF Download',
												'new-tab' => 'Open in a new tab',
											),
											'allow_custom' => 0,
											'default_value' => 'standard-link',
											'layout' => 'vertical',
											'toggle' => 0,
											'return_format' => 'value',
											'save_custom' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),

						// Full Width ------------------------------------------------------
						'full_width_layout' => array(
							'key' => 'flex_field_full_width',
							'name' => 'full_width',
							'label' => 'Full Width',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_full_width_background_color',
									'label' => 'Select Background Color',
									'name' => 'full_width_background_color',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'white' => 'White',
										'gray' => 'Light Gray',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'white',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'flex_field_full_width_text_alignment',
									'label' => 'Select Text Alignment',
									'name' => 'full_width_alignment_options',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'left-align' => 'Left Align',
										'center-align' => 'Center Align',
										'right-align' => 'Right Align',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'left-align',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'flex_field_full_width_headline',
									'label' => 'Headline',
									'name' => 'full_width_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_full_width_content',
									'label' => 'Content',
									'name' => 'full_width_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
								array(
									'key' => 'flex_field_full_width_button_repeater',
									'label' => 'Buttons',
									'name' => 'button_repeater',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'flex_field_full_width_button_label',
											'label' => 'Button Label',
											'name' => 'button_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_full_width_button_link',
											'label' => 'Button Link',
											'name' => 'button_link',
											'type' => 'url',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '40',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array(
											'key' => 'flex_field_full_width_button_link_behavior',
											'label' => 'Link Behavior',
											'name' => 'link_behavior',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '20',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'standard-link' => 'Standard Link',
												'pdf-download' => 'PDF Download',
												'new-tab' => 'Open in a new tab',
											),
											'allow_custom' => 0,
											'default_value' => 'standard-link',
											'layout' => 'vertical',
											'toggle' => 0,
											'return_format' => 'value',
											'save_custom' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),

						// Callout Repeater ------------------------------------------------
						'callout_repeater_layout' => array(
							'key' => 'flex_field_callout_repeater',
							'name' => 'callout_repeater',
							'label' => 'Callout Repeater',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_callout_repeater_section_headline',
									'label' => 'Section Headline',
									'name' => 'callout_section_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_callout_repeater_callouts',
									'label' => 'Callouts',
									'name' => 'callout',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'block',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'flex_field_callout_repeater_small_headline',
											'label' => 'Small Headline',
											'name' => 'callout_small_headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_callout_repeater_large_headline',
											'label' => 'Large Headline',
											'name' => 'callout_large_headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_callout_repeater_content',
											'label' => 'Content',
											'name' => 'callout_content',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 0,
											'delay' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),

						// Callout Repeater ------------------------------------------------
						'expand_collapse_layout' => array(
							'key' => 'flex_field_expand_collapse',
							'name' => 'expand_collapse',
							'label' => 'Expand/Collapse',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_expand_collapse_section_headline',
									'label' => 'Headline',
									'name' => 'expand_collapse_section_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_expand_collapse_repeater',
									'label' => 'Expand/Collapse Items',
									'name' => 'expand_collapse_item',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => 'flex_field_expand_collapse_item_headline',
									'min' => 0,
									'max' => 0,
									'layout' => 'block',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'flex_field_expand_collapse_item_headline',
											'label' => '',
											'name' => 'expand_collapse_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '100',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'flex_field_expand_collapse_item_expanded_content',
											'label' => 'Expanded Content',
											'name' => 'expand_collapse_content',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '100',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 0,
											'delay' => 0,
										),
										array(
											'key' => 'field_expand_collapse_quick_links',
											'label' => 'Quick Links',
											'name' => 'quick_link_repeater',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => '',
											'sub_fields' => array(
												array(
													'key' => 'field_expand_collapse_quick_link_label',
													'label' => 'Link Label',
													'name' => 'link_label',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '40',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_expand_collapse_quick_link_url',
													'label' => 'Link URL',
													'name' => 'link_url',
													'type' => 'url',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '40',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
												),
												array(
													'key' => 'field_expand_collapse_quick_link_behavior',
													'label' => 'Link Behavior',
													'name' => 'link_behavior',
													'type' => 'radio',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '20',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'standard-link' => 'Standard Link',
														'pdf-download' => 'PDF Download',
														'new-tab' => 'Open in a new tab',
													),
													'allow_custom' => 0,
													'default_value' => 'standard-link',
													'layout' => 'vertical',
													'toggle' => 0,
													'return_format' => 'value',
													'save_custom' => 0,
												),
											),
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),

						// Employee Flex ------------------------------------------------
						'employee_flex_layout' => array(
							'key' => 'flex_field_employee_flex',
							'name' => 'employee_flex',
							'label' => 'Employee Contact Cards',
							'display' => 'block',
							'sub_fields' => array(
								array(
		        			'key' => 'field_5c630a00a57db',
		        			'label' => 'Employee Group',
		        			'name' => 'employee_group',
		        			'type' => 'repeater',
		        			'instructions' => '',
		        			'required' => 0,
		        			'conditional_logic' => 0,
		        			'wrapper' => array(
		        				'width' => '',
		        				'class' => '',
		        				'id' => '',
		        			),
		        			'collapsed' => '',
		        			'min' => 0,
		        			'max' => 0,
		        			'layout' => 'table',
		        			'button_label' => '',
		        			'sub_fields' => array(
		        				array(
		        					'key' => 'field_5c630a0fa57dc',
		        					'label' => 'Section Headline',
		        					'name' => 'section_headline',
		        					'type' => 'text',
		        					'instructions' => '',
		        					'required' => 0,
		        					'conditional_logic' => 0,
		        					'wrapper' => array(
		        						'width' => '33',
		        						'class' => '',
		        						'id' => '',
		        					),
		        					'default_value' => '',
		        					'placeholder' => '',
		        					'prepend' => '',
		        					'append' => '',
		        					'maxlength' => '',
		        				),
		        				array(
		        					'key' => 'field_5c630a72a57dd',
		        					'label' => 'Select Employees',
		        					'name' => 'select_employees',
		        					'type' => 'relationship',
		        					'instructions' => '',
		        					'required' => 0,
		        					'conditional_logic' => 0,
		        					'wrapper' => array(
		        						'width' => '66',
		        						'class' => '',
		        						'id' => '',
		        					),
		        					'post_type' => array(
		        						0 => 'employee',
		        					),
		        					'taxonomy' => '',
		        					'filters' => array(
		        						0 => 'search',
		        					),
		        					'elements' => '',
		        					'min' => '',
		        					'max' => '',
		        					'return_format' => 'object',
		        				),
		        			),
		        		),
							),
							'min' => '',
							'max' => '',
						),

						// Employee Flex ------------------------------------------------
						'video_flex_layout' => array(
							'key' => 'flex_field_video_flex',
							'name' => 'video_flex',
							'label' => 'Videos',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_video_section_headline',
									'label' => 'Section Headline',
									'name' => 'flex_video_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_video_section_intro',
									'label' => 'Section Introduction',
									'name' => 'flex_video_intro',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'rows' => 3,
									'maxlength' => '',
								),

								array(
									'key' => 'flex_field_video_button_label',
									'label' => 'Video Page Button Label',
									'name' => 'video_button_label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),

								array(
									'key' => 'flex_field_video_link',
									'label' => 'Vide Page Button Link',
									'name' => 'video_page_link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),

								array(
									'key' => 'field_select_videos',
									'label' => 'Select Videos',
									'name' => 'select_videos',
									'type' => 'relationship',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
										0 => 'video',
									),
									'taxonomy' => '',
									'filters' => array(
										0 => 'search',
									),
									'elements' => '',
									'min' => '',
									'max' => '',
									'return_format' => 'object',
								),

							),
							'min' => '',
							'max' => '',
						),

						// Full Width ------------------------------------------------------
						'membership_calculator_layout' => array(
							'key' => 'flex_field_calculator',
							'name' => 'membership_calculator',
							'label' => 'Membership Calculator',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_membership_calculator_headline',
									'label' => 'Headline',
									'name' => 'membership_calculator_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'flex_field_membership_calculator_content',
									'label' => 'Content',
									'name' => 'membership_calculator_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),

								array(
									'key' => 'flex_field_membership_calculator_disclaimer_content',
									'label' => 'Disclaimer Content',
									'name' => 'membership_calculator_disclaimer_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),


							),
							'min' => '',
							'max' => '',
						),



						// Footer Repeater ------------------------------------------------
						'footer_callout_layout' => array(
							'key' => 'flex_field_footer-callout',
							'name' => 'footer_callout',
							'label' => 'Footer Callout',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'flex_field_footer_callout_headline',
									'label' => 'Headline',
									'name' => 'footer_callout_headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),

								array(
									'key' => 'flex_field_footer_callout_content',
									'label' => 'Content',
									'name' => 'footer_callout_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),


					),
					'button_label' => 'Add Flex Field',
					'min' => '',
					'max' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-flex-content.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

		endif;
	}
}
