<?php
namespace ThemeInfrastructure\ACF;

class ACFHomeFields
{
    public static function setup()
    {
        self::setupHomeFields();
    }
    private static function setupHomeFields()
    {
      if( function_exists('acf_add_local_field_group') ):
        acf_add_local_field_group(array(
        	'key' => 'group_5c78230ad18a9',
        	'title' => 'Logged in Homepage',
        	'fields' => array(
        		array(
        			'key' => 'field_5c78231b9eb0a',
        			'label' => 'Hero Slides',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c7823279eb0b',
        			'label' => 'Logged in Hero Slides',
        			'name' => 'logged_in_hero_slides',
        			'type' => 'repeater',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => 'field_5c78238e9eb0d',
        			'min' => 0,
        			'max' => 0,
        			'layout' => 'table',
        			'button_label' => 'Create A New Slide',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c78235c9eb0c',
        					'label' => 'Logged In Hero Background',
        					'name' => 'logged_in_hero_background',
        					'type' => 'image',
        					'instructions' => 'Select an image for this hero slide',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'return_format' => 'array',
        					'preview_size' => 'thumbnail',
        					'library' => 'all',
        					'min_width' => '',
        					'min_height' => '',
        					'min_size' => '',
        					'max_width' => '',
        					'max_height' => '',
        					'max_size' => '',
        					'mime_types' => '',
        				),
        				array(
        					'key' => 'field_5c78238e9eb0d',
        					'label' => 'Hero Slide Heading',
        					'name' => 'hero_slide_heading',
        					'type' => 'text',
        					'instructions' => 'Enter the header for this hero slide',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c78239d9eb0e',
        					'label' => 'Hero Slide Content',
        					'name' => 'hero_slide_content',
        					'type' => 'textarea',
        					'instructions' => 'Enter content for this hero slide',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'maxlength' => '',
        					'rows' => '',
        					'new_lines' => '',
        				),
        				array(
        					'key' => 'field_5c7823a49eb0f',
        					'label' => 'Hero Slide Button Text',
        					'name' => 'hero_slide_button_text',
        					'type' => 'text',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c7823b29eb10',
        					'label' => 'Hero Slide Button Link',
        					'name' => 'hero_slide_button_link',
        					'type' => 'page_link',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'post_type' => '',
        					'taxonomy' => '',
        					'allow_null' => 0,
        					'allow_archives' => 1,
        					'multiple' => 0,
        				),
        			),
        		),
        		array(
        			'key' => 'field_5c7823fb9eb11',
        			'label' => 'Quick Links',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c7824049eb12',
        			'label' => 'Quick Links Repeater',
        			'name' => 'logged_in_quick_links_repeater',
        			'type' => 'repeater',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => '',
        			'min' => 0,
        			'max' => 0,
        			'layout' => 'table',
        			'button_label' => '',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c78241f9eb13',
        					'label' => 'Button Label',
        					'name' => 'logged_in_quick_links_button_label',
        					'type' => 'text',
        					'instructions' => 'Enter the label text you\'d like to display on this quick links button.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c7824299eb14',
        					'label' => 'Button Caption',
        					'name' => 'logged_in_quick_link_button_caption',
        					'type' => 'text',
        					'instructions' => 'Enter the caption text you\'d like to display on this quick links button.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c7824509eb15',
        					'label' => 'Button Link',
        					'name' => 'logged_in_quick_link_button_link',
        					'type' => 'url',
        					'instructions' => 'Enter the link you\'d like this quick link button to point to.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        				),
        			),
        		),
        		array(
        			'key' => 'field_5c7824939eb16',
        			'label' => 'Latest News',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c7824ad9eb17',
        			'label' => 'Section Heading',
        			'name' => 'news_header',
        			'type' => 'text',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'maxlength' => '',
        		),
        		array(
        			'key' => 'field_5c7824e49eb18',
        			'label' => 'Videos Page Link',
        			'name' => 'video_page_link',
        			'type' => 'page_link',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'page',
        			),
        			'taxonomy' => '',
        			'allow_null' => 0,
        			'allow_archives' => 1,
        			'multiple' => 0,
        		),
        		array(
        			'key' => 'field_5c7825079eb19',
        			'label' => 'News Page Link',
        			'name' => 'news_page_link',
        			'type' => 'page_link',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'page',
        			),
        			'taxonomy' => '',
        			'allow_null' => 0,
        			'allow_archives' => 1,
        			'multiple' => 0,
        		),
            array(
        			'key' => 'field_5c782f3ceebaf',
        			'label' => 'Featured Events',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c782f76eebb0',
        			'label' => 'Featured Events',
        			'name' => 'featured_events',
        			'type' => 'repeater',
        			'instructions' => 'Select which event categories will be featured on the homepage.',
        			'required' => 1,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => 'field_5c78336f10029',
        			'min' => 0,
        			'max' => 5,
        			'layout' => 'table',
        			'button_label' => '',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c78336f10029',
        					'label' => 'Select Event Category',
        					'name' => 'select_event_category',
        					'type' => 'taxonomy',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'taxonomy' => 'tribe_events_cat',
        					'field_type' => 'select',
        					'allow_null' => 0,
        					'add_term' => 1,
        					'save_terms' => 0,
        					'load_terms' => 0,
        					'return_format' => 'object',
        					'multiple' => 0,
        				),
        			),
        		),
        	),
        	'location' => array(
        		array(
        			array(
        				'param' => 'page_type',
        				'operator' => '==',
        				'value' => 'front_page',
        			),
        		),
        	),
        	'menu_order' => 0,
        	'position' => 'normal',
        	'style' => 'default',
        	'label_placement' => 'top',
        	'instruction_placement' => 'label',
        	'hide_on_screen' => '',
        	'active' => 1,
        	'description' => '',
        ));

        acf_add_local_field_group(array(
        	'key' => 'group_5c782604659a5',
        	'title' => 'Logged Out Homepage',
        	'fields' => array(
        		array(
        			'key' => 'field_5c782625e40c2',
        			'label' => 'Hero',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c782633e40c3',
        			'label' => 'Hero Heading',
        			'name' => 'logged_out_hero_heading',
        			'type' => 'text',
        			'instructions' => 'Enter the text you\'d like to display in the hero header',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'maxlength' => '',
        		),
        		array(
        			'key' => 'field_5c782640e40c4',
        			'label' => 'Hero Content',
        			'name' => 'logged_out_hero_content',
        			'type' => 'textarea',
        			'instructions' => 'Enter the text you\'d like to display in the hero content area',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'maxlength' => '',
        			'rows' => 3,
        			'new_lines' => '',
        		),
        		array(
        			'key' => 'field_5c7826c6e40c5',
        			'label' => 'Hero Buttons',
        			'name' => 'logged_out_hero_buttons',
        			'type' => 'repeater',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => 'field_5c7826d5e40c6',
        			'min' => 0,
        			'max' => 0,
        			'layout' => 'table',
        			'button_label' => 'Add Button',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c7826d5e40c6',
        					'label' => 'Button Text',
        					'name' => 'logged_out_hero_button_text',
        					'type' => 'text',
        					'instructions' => 'Enter the text you\'d like to display on this button',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c7826e5e40c7',
        					'label' => 'Button Link',
        					'name' => 'logged_out_hero_button_link',
        					'type' => 'page_link',
        					'instructions' => 'Select the page you\'d like the button to link to',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'post_type' => '',
        					'taxonomy' => '',
        					'allow_null' => 0,
        					'allow_archives' => 1,
        					'multiple' => 0,
        				),
        			),
        		),
        		array(
        			'key' => 'field_5c78271ae40c8',
        			'label' => 'Quick Links',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c782725e40c9',
        			'label' => 'Quick Links',
        			'name' => 'logged_out_quick_links_repeater',
        			'type' => 'repeater',
        			'instructions' => 'Create buttons',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => '',
        			'min' => 0,
        			'max' => 0,
        			'layout' => 'table',
        			'button_label' => '',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c78273ee40ca',
        					'label' => 'Button Label',
        					'name' => 'logged_out_quick_links_button_label',
        					'type' => 'text',
        					'instructions' => 'Enter the label text you\'d like to display on this quick links button.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c782749e40cb',
        					'label' => 'Button Caption',
        					'name' => 'logged_out_quick_link_button_caption',
        					'type' => 'text',
        					'instructions' => 'Enter the caption text you\'d like to display on this quick links button.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c782754e40cc',
        					'label' => 'Button Link',
        					'name' => 'logged_out_quick_link_button_link',
        					'type' => 'url',
        					'instructions' => 'Enter the url you\'d like this quick link button to point to.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        				),
        			),
        		),
        		array(
        			'key' => 'field_5c7827a7e40cd',
        			'label' => 'Flexible Content',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c7827b1e40ce',
        			'label' => 'Flexible Content Fields',
        			'name' => 'flexible_content',
        			'type' => 'flexible_content',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),

              					// Layouts Start Here ------------------------------------------------
              					'layouts' => array(

              						// 50/50 -----------------------------------------------------------
              						'home_50_50_layout' => array(
              							'key' => 'home_field_flex_50_50',
              							'name' => '50_50',
              							'label' => '50/50',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_50_50_background_color',
              									'label' => 'Select Background Color',
              									'name' => '50_50_background_color',
              									'type' => 'radio',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'choices' => array(
              										'white' => 'White',
              										'gray' => 'Light Gray',
              									),
              									'allow_null' => 0,
              									'other_choice' => 0,
              									'default_value' => 'white',
              									'layout' => 'horizontal',
              									'return_format' => 'value',
              									'save_other_choice' => 0,
              								),
              								array(
              									'key' => 'home_field_flex_50_50_section_divider',
              									'label' => 'Section Divider',
              									'name' => '50_50_section_divider',
              									'type' => 'checkbox',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'choices' => array(
              										'yes' => 'Add Divider',
              									),
              									'allow_custom' => 0,
              									'default_value' => array(
              									),
              									'layout' => 'vertical',
              									'toggle' => 0,
              									'return_format' => 'value',
              									'save_custom' => 0,
              								),
              								array(
              									'key' => 'home_field_flex_50_50_section_headline',
              									'label' => 'Section Headline',
              									'name' => '50_50_section_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_field_flex_50_50_section_intro',
              									'label' => 'Section Introduction',
              									'name' => '50_50_section_intro',
              									'type' => 'textarea',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'rows' => 3,
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_field_flex_50_50_left',
              									'label' => 'Left Content',
              									'name' => '50_50_left',
              									'type' => 'group',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'layout' => 'block',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_field_flex_50_50_left_headline',
              											'label' => 'Headline',
              											'name' => '50_50_left_headline',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_field_flex_50_50_left_content',
              											'label' => 'Content',
              											'name' => '50_50_left_content',
              											'type' => 'wysiwyg',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'tabs' => 'all',
              											'toolbar' => 'full',
              											'media_upload' => 1,
              											'delay' => 0,
              										),
              										array(
              											'key' => 'home_flex_field_left_50_50_button_label',
              											'label' => 'Button Label',
              											'name' => '50_50_left_button_label',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_left_50_50_button_link',
              											'label' => 'Button Link',
              											'name' => '50_50_left_button_url',
              											'type' => 'url',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              										),
              									),
              								),
              								array(
              									'key' => 'home_field_flex_50_50_right',
              									'label' => 'Right Content',
              									'name' => '50_50_right',
              									'type' => 'group',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'layout' => 'block',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_field_flex_50_50_right_headline',
              											'label' => 'Headline',
              											'name' => '50_50_right_headline',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_field_flex_50_50_right_content',
              											'label' => 'Content',
              											'name' => '50_50_right_content',
              											'type' => 'wysiwyg',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'tabs' => 'all',
              											'toolbar' => 'full',
              											'media_upload' => 1,
              											'delay' => 0,
              										),
              										array(
              											'key' => 'home_flex_field_right_50_50_button_label',
              											'label' => 'Button Label',
              											'name' => '50_50_right_button_label',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_right_50_50_button_link',
              											'label' => 'Button Link',
              											'name' => '50_50_right_button_url',
              											'type' => 'url',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              										),
              									),
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Image with Text -------------------------------------------------
              						'home_image_text_layout' => array(
              							'key' => 'home_flex_field_image_text',
              							'name' => 'image_with_text',
              							'label' => 'Image with Text',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_image_text_image',
              									'label' => 'Image',
              									'name' => 'image_text_image',
              									'type' => 'image',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'return_format' => 'url',
              									'preview_size' => 'thumbnail',
              									'library' => 'all',
              									'min_width' => '',
              									'min_height' => '',
              									'min_size' => '',
              									'max_width' => '',
              									'max_height' => '',
              									'max_size' => '',
              									'mime_types' => '',
              								),
              								array(
              									'key' => 'home_flex_field_image_text_image_alignment',
              									'label' => 'Select Image Alignment',
              									'name' => 'image_text_alignment_options',
              									'type' => 'radio',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'choices' => array(
              										'left-align' => 'Left Align',
              										'right-align' => 'Right Align',
              									),
              									'allow_null' => 0,
              									'other_choice' => 0,
              									'default_value' => 'left-align',
              									'layout' => 'horizontal',
              									'return_format' => 'value',
              									'save_other_choice' => 0,
              								),
              								array(
              									'key' => 'home_flex_field_image_text_headline',
              									'label' => 'Headline',
              									'name' => 'image_text_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '100',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_flex_field_image_text_content',
              									'label' => 'Content',
              									'name' => 'image_text_content',
              									'type' => 'wysiwyg',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '100',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'tabs' => 'all',
              									'toolbar' => 'basic',
              									'media_upload' => 1,
              									'delay' => 0,
              								),
              								array(
              									'key' => 'home_field_image_text_quick_links',
              									'label' => 'Quick Links',
              									'name' => 'quick_link_repeater',
              									'type' => 'repeater',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'collapsed' => '',
              									'min' => 0,
              									'max' => 0,
              									'layout' => 'table',
              									'button_label' => '',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_field_quick_link_label',
              											'label' => 'Link Label',
              											'name' => 'link_label',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '40',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_field_quick_link_url',
              											'label' => 'Link URL',
              											'name' => 'link_url',
              											'type' => 'url',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '40',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              										),
              										array(
              											'key' => 'home_field_quick_link_behavior',
              											'label' => 'Link Behavior',
              											'name' => 'link_behavior',
              											'type' => 'radio',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '20',
              												'class' => '',
              												'id' => '',
              											),
              											'choices' => array(
              												'standard-link' => 'Standard Link',
              												'pdf-download' => 'PDF Download',
              												'new-tab' => 'Open in a new tab',
              											),
              											'allow_custom' => 0,
              											'default_value' => 'standard-link',
              											'layout' => 'vertical',
              											'toggle' => 0,
              											'return_format' => 'value',
              											'save_custom' => 0,
              										),
              									),
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Full Width ------------------------------------------------------
              						'home_full_width_layout' => array(
              							'key' => 'home_flex_field_full_width',
              							'name' => 'full_width',
              							'label' => 'Full Width',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_full_width_background_color',
              									'label' => 'Select Background Color',
              									'name' => 'full_width_background_color',
              									'type' => 'radio',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'choices' => array(
              										'white' => 'White',
              										'gray' => 'Light Gray',
              									),
              									'allow_null' => 0,
              									'other_choice' => 0,
              									'default_value' => 'white',
              									'layout' => 'horizontal',
              									'return_format' => 'value',
              									'save_other_choice' => 0,
              								),
              								array(
              									'key' => 'home_flex_field_full_width_text_alignment',
              									'label' => 'Select Text Alignment',
              									'name' => 'full_width_alignment_options',
              									'type' => 'radio',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'choices' => array(
              										'left-align' => 'Left Align',
              										'center-align' => 'Center Align',
              										'right-align' => 'Right Align',
              									),
              									'allow_null' => 0,
              									'other_choice' => 0,
              									'default_value' => 'left-align',
              									'layout' => 'horizontal',
              									'return_format' => 'value',
              									'save_other_choice' => 0,
              								),
              								array(
              									'key' => 'home_flex_field_full_width_headline',
              									'label' => 'Headline',
              									'name' => 'full_width_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_flex_field_full_width_content',
              									'label' => 'Content',
              									'name' => 'full_width_content',
              									'type' => 'wysiwyg',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'tabs' => 'all',
              									'toolbar' => 'full',
              									'media_upload' => 0,
              									'delay' => 0,
              								),
              								array(
              									'key' => 'home_flex_field_full_width_button_repeater',
              									'label' => 'Buttons',
              									'name' => 'button_repeater',
              									'type' => 'repeater',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'collapsed' => '',
              									'min' => 0,
              									'max' => 0,
              									'layout' => 'table',
              									'button_label' => '',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_flex_field_full_width_button_label',
              											'label' => 'Button Label',
              											'name' => 'button_label',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '40',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_full_width_button_link',
              											'label' => 'Button Link',
              											'name' => 'button_link',
              											'type' => 'url',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '40',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              										),
              										array(
              											'key' => 'home_flex_field_full_width_button_link_behavior',
              											'label' => 'Link Behavior',
              											'name' => 'link_behavior',
              											'type' => 'radio',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '20',
              												'class' => '',
              												'id' => '',
              											),
              											'choices' => array(
              												'standard-link' => 'Standard Link',
              												'pdf-download' => 'PDF Download',
              												'new-tab' => 'Open in a new tab',
              											),
              											'allow_custom' => 0,
              											'default_value' => 'standard-link',
              											'layout' => 'vertical',
              											'toggle' => 0,
              											'return_format' => 'value',
              											'save_custom' => 0,
              										),
              									),
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Callout Repeater ------------------------------------------------
              						'home_callout_repeater_layout' => array(
              							'key' => 'home_flex_field_callout_repeater',
              							'name' => 'callout_repeater',
              							'label' => 'Callout Repeater',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_callout_repeater_section_headline',
              									'label' => 'Section Headline',
              									'name' => 'callout_section_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_flex_field_callout_repeater_callouts',
              									'label' => 'Callouts',
              									'name' => 'callout',
              									'type' => 'repeater',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'collapsed' => '',
              									'min' => 0,
              									'max' => 0,
              									'layout' => 'block',
              									'button_label' => '',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_flex_field_callout_repeater_small_headline',
              											'label' => 'Small Headline',
              											'name' => 'callout_small_headline',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_callout_repeater_large_headline',
              											'label' => 'Large Headline',
              											'name' => 'callout_large_headline',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_callout_repeater_content',
              											'label' => 'Content',
              											'name' => 'callout_content',
              											'type' => 'wysiwyg',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'tabs' => 'all',
              											'toolbar' => 'full',
              											'media_upload' => 0,
              											'delay' => 0,
              										),
              									),
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Callout Repeater ------------------------------------------------
              						'home_expand_collapse_layout' => array(
              							'key' => 'home_flex_field_expand_collapse',
              							'name' => 'expand_collapse',
              							'label' => 'Expand/Collapse',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_expand_collapse_repeater',
              									'label' => 'Expand/Collapse Items',
              									'name' => 'expand_collapse_item',
              									'type' => 'repeater',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'collapsed' => 'home_flex_field_expand_collapse_item_headline',
              									'min' => 0,
              									'max' => 0,
              									'layout' => 'block',
              									'button_label' => '',
              									'sub_fields' => array(
              										array(
              											'key' => 'home_flex_field_expand_collapse_item_headline',
              											'label' => '',
              											'name' => 'expand_collapse_label',
              											'type' => 'text',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '100',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'placeholder' => '',
              											'prepend' => '',
              											'append' => '',
              											'maxlength' => '',
              										),
              										array(
              											'key' => 'home_flex_field_expand_collapse_item_expanded_content',
              											'label' => 'Expanded Content',
              											'name' => 'expand_collapse_content',
              											'type' => 'wysiwyg',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '100',
              												'class' => '',
              												'id' => '',
              											),
              											'default_value' => '',
              											'tabs' => 'all',
              											'toolbar' => 'full',
              											'media_upload' => 0,
              											'delay' => 0,
              										),
              										array(
              											'key' => 'home_field_expand_collapse_quick_links',
              											'label' => 'Quick Links',
              											'name' => 'quick_link_repeater',
              											'type' => 'repeater',
              											'instructions' => '',
              											'required' => 0,
              											'conditional_logic' => 0,
              											'wrapper' => array(
              												'width' => '',
              												'class' => '',
              												'id' => '',
              											),
              											'collapsed' => '',
              											'min' => 0,
              											'max' => 0,
              											'layout' => 'table',
              											'button_label' => '',
              											'sub_fields' => array(
              												array(
              													'key' => 'home_field_expand_collapse_quick_link_label',
              													'label' => 'Link Label',
              													'name' => 'link_label',
              													'type' => 'text',
              													'instructions' => '',
              													'required' => 0,
              													'conditional_logic' => 0,
              													'wrapper' => array(
              														'width' => '40',
              														'class' => '',
              														'id' => '',
              													),
              													'default_value' => '',
              													'placeholder' => '',
              													'prepend' => '',
              													'append' => '',
              													'maxlength' => '',
              												),
              												array(
              													'key' => 'home_field_expand_collapse_quick_link_url',
              													'label' => 'Link URL',
              													'name' => 'link_url',
              													'type' => 'url',
              													'instructions' => '',
              													'required' => 0,
              													'conditional_logic' => 0,
              													'wrapper' => array(
              														'width' => '40',
              														'class' => '',
              														'id' => '',
              													),
              													'default_value' => '',
              													'placeholder' => '',
              												),
              												array(
              													'key' => 'home_field_expand_collapse_quick_link_behavior',
              													'label' => 'Link Behavior',
              													'name' => 'link_behavior',
              													'type' => 'radio',
              													'instructions' => '',
              													'required' => 0,
              													'conditional_logic' => 0,
              													'wrapper' => array(
              														'width' => '20',
              														'class' => '',
              														'id' => '',
              													),
              													'choices' => array(
              														'standard-link' => 'Standard Link',
              														'pdf-download' => 'PDF Download',
              														'new-tab' => 'Open in a new tab',
              													),
              													'allow_custom' => 0,
              													'default_value' => 'standard-link',
              													'layout' => 'vertical',
              													'toggle' => 0,
              													'return_format' => 'value',
              													'save_custom' => 0,
              												),
              											),
              										),
              									),
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Employee Flex ------------------------------------------------
              						'home_employee_flex_layout' => array(
              							'key' => 'home_flex_field_employee_flex',
              							'name' => 'employee_flex',
              							'label' => 'Employee Contact Cards',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              		        			'key' => 'home_field_5c630a00a57db',
              		        			'label' => 'Employee Group',
              		        			'name' => 'employee_group',
              		        			'type' => 'repeater',
              		        			'instructions' => '',
              		        			'required' => 0,
              		        			'conditional_logic' => 0,
              		        			'wrapper' => array(
              		        				'width' => '',
              		        				'class' => '',
              		        				'id' => '',
              		        			),
              		        			'collapsed' => '',
              		        			'min' => 0,
              		        			'max' => 0,
              		        			'layout' => 'table',
              		        			'button_label' => '',
              		        			'sub_fields' => array(
              		        				array(
              		        					'key' => 'home_field_5c630a0fa57dc',
              		        					'label' => 'Section Headline',
              		        					'name' => 'section_headline',
              		        					'type' => 'text',
              		        					'instructions' => '',
              		        					'required' => 0,
              		        					'conditional_logic' => 0,
              		        					'wrapper' => array(
              		        						'width' => '33',
              		        						'class' => '',
              		        						'id' => '',
              		        					),
              		        					'default_value' => '',
              		        					'placeholder' => '',
              		        					'prepend' => '',
              		        					'append' => '',
              		        					'maxlength' => '',
              		        				),
              		        				array(
              		        					'key' => 'home_field_5c630a72a57dd',
              		        					'label' => 'Select Employees',
              		        					'name' => 'select_employees',
              		        					'type' => 'relationship',
              		        					'instructions' => '',
              		        					'required' => 0,
              		        					'conditional_logic' => 0,
              		        					'wrapper' => array(
              		        						'width' => '66',
              		        						'class' => '',
              		        						'id' => '',
              		        					),
              		        					'post_type' => array(
              		        						0 => 'employee',
              		        					),
              		        					'taxonomy' => '',
              		        					'filters' => array(
              		        						0 => 'search',
              		        					),
              		        					'elements' => '',
              		        					'min' => '',
              		        					'max' => '',
              		        					'return_format' => 'object',
              		        				),
              		        			),
              		        		),
              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Employee Flex ------------------------------------------------
              						'home_video_flex_layout' => array(
              							'key' => 'home_flex_field_video_flex',
              							'name' => 'video_flex',
              							'label' => 'Videos',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_video_section_headline',
              									'label' => 'Section Headline',
              									'name' => 'flex_video_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),
              								array(
              									'key' => 'home_flex_field_video_section_intro',
              									'label' => 'Section Introduction',
              									'name' => 'flex_video_intro',
              									'type' => 'textarea',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'rows' => 3,
              									'maxlength' => '',
              								),

              								array(
              									'key' => 'home_flex_field_video_button_label',
              									'label' => 'Video Page Button Label',
              									'name' => 'video_button_label',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),

              								array(
              									'key' => 'home_flex_field_video_link',
              									'label' => 'Vide Page Button Link',
              									'name' => 'video_page_link',
              									'type' => 'page_link',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '50',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              								),

              								array(
              									'key' => 'home_field_select_videos',
              									'label' => 'Select Videos',
              									'name' => 'select_videos',
              									'type' => 'relationship',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'post_type' => array(
              										0 => 'video',
              									),
              									'taxonomy' => '',
              									'filters' => array(
              										0 => 'search',
              									),
              									'elements' => '',
              									'min' => '',
              									'max' => '',
              									'return_format' => 'object',
              								),

              							),
              							'min' => '',
              							'max' => '',
              						),

              						// Footer Repeater ------------------------------------------------
              						'home_footer_callout_layout' => array(
              							'key' => 'home_flex_field_footer-callout',
              							'name' => 'footer_callout',
              							'label' => 'Footer Callout',
              							'display' => 'block',
              							'sub_fields' => array(
              								array(
              									'key' => 'home_flex_field_footer_callout_headline',
              									'label' => 'Headline',
              									'name' => 'footer_callout_headline',
              									'type' => 'text',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'placeholder' => '',
              									'prepend' => '',
              									'append' => '',
              									'maxlength' => '',
              								),

              								array(
              									'key' => 'home_flex_field_footer_callout_content',
              									'label' => 'Content',
              									'name' => 'footer_callout_content',
              									'type' => 'wysiwyg',
              									'instructions' => '',
              									'required' => 0,
              									'conditional_logic' => 0,
              									'wrapper' => array(
              										'width' => '',
              										'class' => '',
              										'id' => '',
              									),
              									'default_value' => '',
              									'tabs' => 'all',
              									'toolbar' => 'full',
              									'media_upload' => 0,
              									'delay' => 0,
              								),
              							),
              							'min' => '',
              							'max' => '',
              						),


              					),
              					'button_label' => 'Add Flex Field',
              					'min' => '',
              					'max' => '',
        		),
        	),
        	'location' => array(
        		array(
        			array(
        				'param' => 'page_type',
        				'operator' => '==',
        				'value' => 'front_page',
        			),
        		),
        	),
        	'menu_order' => 0,
        	'position' => 'normal',
        	'style' => 'default',
        	'label_placement' => 'top',
        	'instruction_placement' => 'label',
        	'hide_on_screen' => '',
        	'active' => 1,
        	'description' => '',
        ));

        endif;
    }
}
