<?php
namespace ThemeInfrastructure\ACF;

class ACFJumpToFields
{

    public static function setup()
    {
        self::setupJumpToFields();
    }

    private static function setupJumpToFields()
    {
      if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
        	'key' => 'group_5c896ffd04ab7',
        	'title' => 'Page Content',
        	'fields' => array(
        		array(
        			'key' => 'field_5c89701d5a48b',
        			'label' => 'Introduction Content',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c89707e5a48c',
        			'label' => 'Heading',
        			'name' => 'introduction_heading',
        			'type' => 'text',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'maxlength' => '',
        		),
        		array(
        			'key' => 'field_5c8970925a48d',
        			'label' => 'Content',
        			'name' => 'introduction_content',
        			'type' => 'wysiwyg',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'tabs' => 'all',
        			'toolbar' => 'full',
        			'media_upload' => 1,
        			'delay' => 0,
        		),
            array(
              'key' => 'field_intro_button_label',
              'label' => 'Link Label',
              'name' => 'link_label',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_intro_button_url',
              'label' => 'Link URL',
              'name' => 'link_url',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_intro_button_behavior',
              'label' => 'Link Behavior',
              'name' => 'link_behavior',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'standard-link' => 'Standard Link',
                'pdf-download' => 'PDF Download',
                'new-tab' => 'Open in a new tab',
              ),
              'allow_custom' => 0,
              'default_value' => 'standard-link',
              'layout' => 'vertical',
              'toggle' => 0,
              'return_format' => 'value',
              'save_custom' => 0,
            ),
        		array(
        			'key' => 'field_5c8971945a494',
        			'label' => 'Page Sections',
        			'name' => '',
        			'type' => 'tab',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'placement' => 'top',
        			'endpoint' => 0,
        		),
        		array(
        			'key' => 'field_5c8970ec5a490',
        			'label' => 'Page Sections',
        			'name' => 'page_sections',
        			'type' => 'repeater',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => '',
        			'min' => 0,
        			'max' => 0,
        			'layout' => 'block',
        			'button_label' => '',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_5c8970ff5a491',
        					'label' => 'Heading',
        					'name' => 'section_heading',
        					'type' => 'text',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c8971135a492',
        					'label' => 'Anchor',
        					'name' => 'anchor',
        					'type' => 'text',
        					'instructions' => 'Ex. sectionOne. Include no spaces, special characters or numbers.',
        					'required' => 1,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'maxlength' => '',
        				),
        				array(
        					'key' => 'field_5c89716e5a493',
        					'label' => 'Content',
        					'name' => 'section_content',
        					'type' => 'wysiwyg',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'tabs' => 'all',
        					'toolbar' => 'full',
        					'media_upload' => 1,
        					'delay' => 0,
        				),
        			),
        		),
        	),
        	'location' => array(
        		array(
        			array(
        				'param' => 'page_template',
        				'operator' => '==',
        				'value' => 'page-jump-to.php',
        			),
        		),
        	),
        	'menu_order' => 0,
        	'position' => 'normal',
        	'style' => 'default',
        	'label_placement' => 'top',
        	'instruction_placement' => 'label',
        	'hide_on_screen' => array(
        		0 => 'the_content',
        		1 => 'excerpt',
        		2 => 'discussion',
        		3 => 'comments',
        		4 => 'categories',
        		5 => 'tags',
        		6 => 'send-trackbacks',
        	),
        	'active' => 1,
        	'description' => '',
        ));

        endif;

      if( function_exists('acf_add_local_field_group') ):

          acf_add_local_field_group(array(
          	'key' => 'group_5c8a998788398',
          	'title' => 'Committees',
          	'fields' => array(
              array(
                'key' => 'field_5c89701d5a48b_committees',
                'label' => 'Introduction Content',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_5c89707e5a48c_committees',
                'label' => 'Heading',
                'name' => 'introduction_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5c8970925a48d_committees',
                'label' => 'Content',
                'name' => 'introduction_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
              ),
              array(
                'key' => 'field_committees_intro_button_label',
                'label' => 'Link Label',
                'name' => 'link_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_committees_intro_button_url',
                'label' => 'Link URL',
                'name' => 'link_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_committees_intro_button_behavior',
                'label' => 'Link Behavior',
                'name' => 'intro_link_behavior',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '20',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'standard-link' => 'Standard Link',
                  'pdf-download' => 'PDF Download',
                  'new-tab' => 'Open in a new tab',
                ),
                'allow_custom' => 0,
                'default_value' => 'standard-link',
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
              ),
          		array(
          			'key' => 'field_5c8a9993b985c',
          			'label' => 'Committees',
          			'name' => '',
          			'type' => 'tab',
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array(
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'placement' => 'top',
          			'endpoint' => 0,
          		),
          		array(
          			'key' => 'field_5c8a99d3b985d',
          			'label' => 'Add Committees',
          			'name' => 'add_committees',
          			'type' => 'repeater',
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array(
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'collapsed' => 'field_5c8a99e4b985e',
          			'min' => 0,
          			'max' => 0,
          			'layout' => 'block',
          			'button_label' => 'Add Committee',
          			'sub_fields' => array(
          				array(
          					'key' => 'field_5c8a99e4b985e',
          					'label' => 'Committee Name',
          					'name' => 'committee_name',
          					'type' => 'text',
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '',
          						'class' => '',
          						'id' => '',
          					),
          					'default_value' => '',
          					'placeholder' => '',
          					'prepend' => '',
          					'append' => '',
          					'maxlength' => '',
          				),
          				array(
          					'key' => 'field_5c8a99f5b985f',
          					'label' => 'Anchor',
          					'name' => 'anchor',
          					'type' => 'text',
          					'instructions' => 'Ex. sectionOne. Include no spaces, special characters or numbers.',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '',
          						'class' => '',
          						'id' => '',
          					),
          					'default_value' => '',
          					'placeholder' => '',
          					'prepend' => '',
          					'append' => '',
          					'maxlength' => '',
          				),
          				array(
          					'key' => 'field_5c8a99fcb9860',
          					'label' => 'Committee Description',
          					'name' => 'committee_description',
          					'type' => 'wysiwyg',
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '',
          						'class' => '',
          						'id' => '',
          					),
          					'default_value' => '',
          					'placeholder' => '',
          					'prepend' => '',
          					'append' => '',
          					'maxlength' => '',
          				),
                  array(
          					'key' => 'field_5c8aa1501e875',
          					'label' => 'Roster PDF',
          					'name' => 'roster_pdf',
          					'type' => 'file',
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '50',
          						'class' => '',
          						'id' => '',
          					),
          					'return_format' => 'array',
          					'library' => 'all',
          					'min_size' => '',
          					'max_size' => '',
          					'mime_types' => '',
          				),
                  array(
                    'key' => 'field_5c8aa1501e87523',
                    'label' => 'Executive Roster PDF',
                    'name' => 'executive_roster_pdf',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
          				array(
          					'key' => 'field_5c8aa18d1e876',
          					'label' => 'Committee Meetings',
          					'name' => 'committee_meetings',
          					'type' => 'relationship',
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '50',
          						'class' => '',
          						'id' => '',
          					),
          					'post_type' => array(
          						0 => 'tribe_events',
          					),
          					// 'taxonomy' => array(
          					// 	0 => 'tribe_events_cat:committees',
          					// ),
          					'filters' => array(
          						0 => 'search',
          					),
          					'elements' => '',
          					'min' => '',
          					'max' => '',
          					'return_format' => 'object',
          				),

                  array(
                    'key' => 'field_5c8aa18d1e876234',
                    'label' => 'Executive Committee Meetings',
                    'name' => 'executive_committee_meetings',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                      0 => 'tribe_events',
                    ),
                    // 'taxonomy' => array(
                    //   0 => 'tribe_events_cat:committees',
                    // ),
                    'filters' => array(
                      0 => 'search',
                    ),
                    'elements' => '',
                    'min' => '',
                    'max' => '',
                    'return_format' => 'object',
                  ),
          				array(
          					'key' => 'field_5c8a9ae5b9861',
          					'label' => 'Tabs',
          					'name' => 'tabs',
          					'type' => 'repeater',
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array(
          						'width' => '',
          						'class' => '',
          						'id' => '',
          					),
          					'collapsed' => 'field_5c8a9b2bb9862',
          					'min' => 0,
          					'max' => 0,
          					'layout' => 'row',
          					'button_label' => 'Add Tab',
          					'sub_fields' => array(
          						array(
          							'key' => 'field_5c8a9b2bb9862',
          							'label' => 'Tab Title',
          							'name' => 'tab_title',
          							'type' => 'text',
          							'instructions' => '',
          							'required' => 0,
          							'conditional_logic' => 0,
          							'wrapper' => array(
          								'width' => '',
          								'class' => '',
          								'id' => '',
          							),
          							'default_value' => '',
          							'placeholder' => '',
          							'prepend' => '',
          							'append' => '',
          							'maxlength' => '',
          						),
          						array(
          							'key' => 'field_5c8a9b34b9863',
          							'label' => 'Tab Content',
          							'name' => 'tab_content',
          							'type' => 'wysiwyg',
          							'instructions' => '',
          							'required' => 0,
          							'conditional_logic' => 0,
          							'wrapper' => array(
          								'width' => '',
          								'class' => '',
          								'id' => '',
          							),
          							'default_value' => '',
          							'tabs' => 'all',
          							'toolbar' => 'full',
          							'media_upload' => 1,
          							'delay' => 0,
          						),
          						array(
          							'key' => 'field_5c8a9b3bb9864',
          							'label' => 'Employee Card',
          							'name' => 'employee_card',
          							'type' => 'post_object',
          							'instructions' => '',
          							'required' => 0,
          							'conditional_logic' => 0,
          							'wrapper' => array(
          								'width' => '',
          								'class' => '',
          								'id' => '',
          							),
          							'post_type' => array(
          								0 => 'employee',
          							),
          							'taxonomy' => '',
          							'allow_null' => 0,
          							'multiple' => 0,
          							'return_format' => 'object',
          							'ui' => 1,
          						),
          					),
          				),
          			),
          		),
          	),
          	'location' => array(
          		array(
          			array(
          				'param' => 'page_template',
          				'operator' => '==',
          				'value' => 'page-committees.php',
          			),
          		),
          	),
          	'menu_order' => 0,
          	'position' => 'normal',
          	'style' => 'default',
          	'label_placement' => 'top',
          	'instruction_placement' => 'label',
          	'hide_on_screen' => '',
          	'active' => 1,
          	'description' => '',
          ));

          endif;
    }

}
