//Blog/Stories list view ajax loading
(function($) {
    var pageNumber;
    var defaultPPP;
    var hasSetFilterHTML;
    var hasSetSortHTML;
    var listContainer;
    var filterContainer;
    //var paginationContainer;


    var currentCategory = null;
    var currentSearch = "";
    var currentSort = false;

  function load_blog_list(search, filter, sort, page, ppp, clearPagination){

      ppp = ppp || defaultPPP;
      clearPagination = clearPagination || false;
      pageNumber = page;
      sort = sort || false;


      var data = {
        search: search,
        filter: filter,
        page: pageNumber,
        ppp: ppp,
        clearPagination: clearPagination,
        sort: sort
      }

      $.ajax({
        url: VideoHelper.video_endpoint,
        type: "POST",
        dataType: "html",
        data: data,
        cache: false,
        beforeSend: function(xhr){
            xhr.setRequestHeader( 'X-WP-Nonce', rest_object.api_nonce );
            $('.loading_spinner').addClass('active');
          },
        success : function( response ) {
          var parsedResponse = $.parseJSON(response);

          if(!hasSetFilterHTML){
            var filterHTML = parsedResponse["blog_data"]["filter_html"];
            filterContainer.append(filterHTML);

            //bind filter change event after filters have been created
            $("#select-filter-blogs").change(OnChangeStyle);

            $("#select-filter-search").change(OnChangeSearch);

            $('.blog-filter-clear').css("display","none");

            $('.blog-filter-clear').on('click', function(e){
               e.preventDefault();
               clearVars();
               $("#select-filter-blogs").val("all");
               $("#select-filter-search").val("");

               $('.blog-filter-clear').css("display","none");
               $('.category-title').html("");
               $('.category-description').html("");
               $('.post-category_container').css("display","none");

               load_blog_list(currentSearch, currentCategory, currentSort, pageNumber, defaultPPP, true);
            });

            //filter values may have been passed by url, update filters if that's the case
            if(currentCategory){
              setFilterValueFromParam('#select-filter-blogs', currentCategory);
            }

            //filter values may have been passed by url, update filters if that's the case
            if(currentSearch){
              setFilterValueFromParam('#select-filter-search', currentSearch);
            }

            hasSetFilterHTML = true;
          }

          if(!hasSetSortHTML){
            var sortHTML = parsedResponse["blog_data"]["sort_html"];
            sortContainer.append(sortHTML);

            //video sort buttons are also generated by video listing helper
            //need to add click event to each after they've been generated
            $(".video-sort button.sort").each(function () {
              $(this).on('click', function (e) {
                OnSort(e);
              })
            })

            hasSetSortHTML = true;
          }

          var blogHTML = parsedResponse["blog_data"]["blogs_html"];
          listContainer.html(blogHTML);

          var paginationHTML = parsedResponse["blog_data"]["pagination_html"];
          paginationContainer.html(paginationHTML);

          $('.pagination_link:not(.disabled)').on('click', function(e){
            e.preventDefault();
            onClickPagination(this);
          })

          $('.pagination_link.disabled').removeAttr('href');

          pageNumber++;
        },
        fail : function( response ) {
          console.log('fail!');
          console.log(response);

          listContainer.append('<p>Sorry, no posts can be loaded.</p>');
        },
        complete : function(){
          $('.loading_spinner').removeClass('active');
        }
      });
    }

    function OnChangeStyle(){
      pageNumber = 1;
      previousCount = -1;
      currentCategory = $(this).val();
      load_blog_list(currentSearch, currentCategory, currentSort, pageNumber, defaultPPP, true);

      $('.blog-filter-clear').css("display","block");

      catName = $(this).find('option:selected').attr("name");
      catDescription = $(this).find('option:selected').attr("data-description");

      $('.post-category_container').css("display","block");
      $('.category-title').html(catName);
      $('.category-description').html(catDescription);
    }

    function OnChangeSearch(){
      pageNumber = 1;
      previousCount = -1;
      currentSearch = $(this).val();
      load_blog_list(currentSearch, currentCategory, currentSort, pageNumber, defaultPPP, true);
      $('.blog-filter-clear').css("display","block");
    }

    function OnSort(e){
      e.preventDefault();
      pageNumber = 1;
      previousCount = -1;
      currentSort = $(e.target).attr("data-sort");

      $(".video-sort button.sort").removeClass('active');
      $(e.target).addClass('active');
      //console.log(currentSort)
      load_blog_list(currentSearch, currentCategory, currentSort, pageNumber, defaultPPP, true);
    }

    function onClickPagination(item){
      pageNumber = $(item).data('page');
      load_blog_list(currentSearch, currentCategory, currentSort, pageNumber, defaultPPP, true);
    }

    function setFilterValueFromParam(selector, param){
      if($(selector + " option[value='" + param + "']").length > 0){
        $(selector).val(param);
      }
    }

    function clearVars(){
      currentSearch = "";
      currentCategory = null;
      pageNumber = 1;
      previousCount = -1;
      catName = null;
      catDescription = null;
      currentSort = false;
    }

    function parseQueryParams(){
      var match
      var pl = /\+/g  // Regex for replacing addition symbol with a space
      var search = /([^&=]+)=?([^&]*)/g
      var decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); }
      var query  = window.location.search.substring(1)
      var urlParams = {}

      if(query){
        while (match = search.exec(query)){
          urlParams[decode(match[1])] = decode(match[2])
        }
      }

      return urlParams
    }

    $(document).ready(function(){
      pageNumber = 1;
      defaultPPP = 12;
      hasSetFilterHTML = false;
      hasSetSortHTML = false;
      listContainer = $(".video-listing_container");
      filterContainer = $(".posts-filter_container");
      sortContainer = $(".posts-sort_container");
      paginationContainer = $(".posts-pagination_container");


      //parseQueryParams may throw an error if the url is malformed
      try{
        var queryParams = parseQueryParams();
        if(queryParams.filter){
          currentCategory = queryParams.filter;
        }

        if(queryParams.search ){
          currentSearch = queryParams.search;
        }

      }catch(e){
        console.log(e)
      }

      load_blog_list(currentSearch, currentCategory, currentSort, pageNumber);

    });
  })(jQuery);
